#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
EIM Expansions Data File
Contains all text expansions from the original EIM.ahk file
"""

# Complete text expansions data
EXPANSIONS_DATA = {
    # Text abbreviation expansions
    "aomg": "oh my god",
    "Aomg": "Oh my god",
    "abtw": "by the way",
    "Abtw": "By the way",
    "aidk": "i don't know",
    "Aidk": "I don't know",
    "aimho": "in my humble opinion",
    "Aimho": "In my humble opinion",
    "afyi": "for your information",
    "Afyi": "For your information",
    "aasap": "as soon as possible",
    "Aasap": "As soon as possible",
    "alol": "laugh out loud",
    "Alol": "Laugh out loud",
    "abrb": "be right back",
    "Abrb": "Be right back",
    "attyl": "talk to you later",
    "Attyl": "Talk to you later",
    "aty": "thank you",
    "Aty": "Thank you",
    "afaik": "as far as i know",
    "Afaik": "As far as I know",
    
    # Legal phrase expansions
    "lainre": "in reference to the matter of",
    "LAinre": "In reference to the matter of",
    "lahere": "subject to the provisions hereof",
    "LAhere": "Subject to the provisions hereof",
    "lawith": "without prejudice to the foregoing",
    "LAwith": "Without prejudice to the foregoing",
    "laprior": "prior to the execution hereof",
    "LAprior": "Prior to the execution hereof",
    "laterm": "for the term set forth herein",
    "LAterm": "For the term set forth herein",
    "labreach": "in the event of any breach thereof",
    "LAbreach": "In the event of any breach thereof",
    "lalaw": "pursuant to applicable law",
    "LAlaw": "Pursuant to applicable law",
    "laagree": "for and in consideration of the mutual covenants",
    "LAagree": "For and in consideration of the mutual covenants",
    "lareg": "in accordance with applicable regulations",
    "LAreg": "In accordance with applicable regulations",
    "lacomp": "in compliance with all relevant requirements",
    "LAcomp": "In compliance with all relevant requirements",
    "laconf": "subject to confidentiality obligations",
    "LAconf": "Subject to confidentiality obligations",
    "laliab": "shall not be liable for any damages arising from",
    "LAliab": "Shall not be liable for any damages arising from",
    "lawar": "represents and warrants that",
    "LAwar": "Represents and warrants that",
    "laind": "shall indemnify and hold harmless",
    "LAind": "Shall indemnify and hold harmless",
    "lasev": "if any provision is found to be invalid or unenforceable",
    "LAsev": "If any provision is found to be invalid or unenforceable",
    
    # Word completion expansions (replaces suffix functionality)
    # n- prefix (words ending in -cation) - removed common "ifi" letters
    # Ordered alphabetically by full word
    "nampla": "amplification",
    "Nampla": "Amplification", 
    "nbeauta": "beautification",
    "Nbeauta": "Beautification",
    "ncalca": "calcification", 
    "Ncalca": "Calcification",
    "ncerta": "certification",
    "Ncerta": "Certification",
    "nclara": "clarification",
    "Nclara": "Clarification",
    "nclassa": "classification",
    "Nclassa": "Classification",
    "ndigna": "dignification",
    "Ndigna": "Dignification",
    "ndiversa": "diversification",
    "Ndiversa": "Diversification",
    "nforta": "fortification",
    "Nforta": "Fortification",
    "ngasa": "gasification",
    "Ngasa": "Gasification",
    "nglora": "glorification",
    "Nglora": "Glorification",
    "ngrata": "gratification",
    "Ngrata": "Gratification",
    "nidenta": "identification",
    "Nidenta": "Identification",
    "nintensa": "intensification",
    "Nintensa": "Intensification",
    "njusta": "justification",
    "Njusta": "Justification",
    "nliqua": "liquification",
    "Nliqua": "Liquification",
    "nmagna": "magnification",
    "Nmagna": "Magnification",
    "nmoda": "modification",
    "Nmoda": "Modification",
    "nmuma": "mummification",
    "Nmuma": "Mummification",
    "nmysta": "mystification",
    "Nmysta": "Mystification",
    "nossa": "ossification",
    "Nossa": "Ossification",
    "npaca": "pacification",
    "Npaca": "Pacification",
    "npersona": "personification",
    "Npersona": "Personification",
    "npetra": "petrification",
    "Npetra": "Petrification",
    "npura": "purification",
    "Npura": "Purification",
    "nquala": "qualification",
    "Nquala": "Qualification",
    "nrama": "ramification",
    "Nrama": "Ramification",
    "nrata": "ratification",
    "Nrata": "Ratification",
    "nsancta": "sanctification",
    "Nsancta": "Sanctification",
    "nsigna": "signification",
    "Nsigna": "Signification",
    "nsimpla": "simplification",
    "Nsimpla": "Simplification",
    "nsolida": "solidification",
    "Nsolida": "Solidification",
    "nspeca": "specification",
    "Nspeca": "Specification",
    "nstrata": "stratification",
    "Nstrata": "Stratification",
    "ntesta": "testification",
    "Ntesta": "Testification",
    "nunifa": "unification",
    "Nunifa": "Unification",
    "nvera": "verification",
    "Nvera": "Verification",

    # n- prefix (words ending in -ation, -sion, -sion) - removed common letters
    # Ordered alphabetically by full word
    "nadmina": "administration",
    "Nadmina": "Administration",
    "ncommu": "communication", 
    "Ncommu": "Communication",
    "nconca": "concentration",
    "Nconca": "Concentration",
    "nconca": "conclusion",
    "Nconca": "Conclusion",
    "nconfa": "confusion",
    "Nconfa": "Confusion",
    "nconsa": "consideration",
    "Nconsa": "Consideration",
    "ndea": "decision",
    "Ndea": "Decision",
    "ndemo": "demonstration",
    "Ndemo": "Demonstration",
    "ndeterma": "determination",
    "Ndeterma": "Determination",
    "ndiva": "division",
    "Ndiva": "Division",
    "neduca": "education",
    "Neduca": "Education",
    "nexa": "examination",
    "Nexa": "Examination",
    "ngena": "generation",
    "Ngena": "Generation",
    "ninfora": "information",
    "Ninfora": "Information",
    "ninvesta": "investigation",
    "Ninvesta": "Investigation",
    "nopera": "operation",
    "Nopera": "Operation",
    "norgana": "organization",
    "Norgana": "Organization",
    "nprepa": "preparation",
    "Nprepa": "Preparation",
    "nproa": "provision",
    "Nproa": "Provision",
    "nreco": "recommendation",
    "Nreco": "Recommendation",
    "nrepa": "representation",
    "Nrepa": "Representation",
    "nreva": "revision",
    "Nreva": "Revision",
    "nsitua": "situation",
    "Nsitua": "Situation",
    "nsupa": "supervision",
    "Nsupa": "Supervision",
    "ntelea": "television",
    "Ntelea": "Television",

    # t- prefix (words ending in -ive) - removed common letters
    # Ordered alphabetically by full word
    "tcomprehen": "comprehensive",
    "Tcomprehen": "Comprehensive",
    "tdefen": "defensive",
    "Tdefen": "Defensive",
    "texpen": "expensive",
    "Texpen": "Expensive", 
    "texten": "extensive",
    "Texten": "Extensive",
    "tinten": "intensive",
    "Tinten": "Intensive",
    "toffen": "offensive",
    "Toffen": "Offensive",

    # -ation suffix (words ending in -ation) - removed common letters
    # Ordered alphabetically by full word
    "tapprea": "appreciation",
    "Tapprea": "Appreciation",
    "tassoa": "association", 
    "Tassoa": "Association",
    "tcompen": "compensation",
    "Tcompen": "Compensation",
    "tcoopa": "cooperation",
    "Tcoopa": "Cooperation",
    "tevala": "evaluation",
    "Tevala": "Evaluation",
    "tinda": "indication",
    "Tinda": "Indication",
    "tlegi": "legislation",
    "Tlegi": "Legislation",
    "tmeda": "medication",
    "Tmeda": "Medication",
    "tnego": "negotiation",
    "Tnego": "Negotiation",
    "tregu": "regulation",
    "Tregu": "Regulation",

    # Special cases (unique patterns)
    "ncondi": "condition",
    "Ncondi": "Condition",
    
    # US states and territories
    "USal": "Alabama", "USak": "Alaska", "USaz": "Arizona",
    "USar": "Arkansas", "USca": "California", "USco": "Colorado",
    "USct": "Connecticut", "USde": "Delaware", "USfl": "Florida",
    "USga": "Georgia", "UShi": "Hawaii", "USid": "Idaho",
    "USil": "Illinois", "USin": "Indiana", "USia": "Iowa",
    "USks": "Kansas", "USky": "Kentucky", "USla": "Louisiana",
    "USme": "Maine", "USmd": "Maryland", "USma": "Massachusetts",
    "USmi": "Michigan", "USmn": "Minnesota", "USms": "Mississippi",
    "USmo": "Missouri", "USmt": "Montana", "USne": "Nebraska",
    "USnv": "Nevada", "USnh": "New Hampshire", "USnj": "New Jersey",
    "USnm": "New Mexico", "USny": "New York", "USnc": "North Carolina",
    "USnd": "North Dakota", "USoh": "Ohio", "USok": "Oklahoma",
    "USor": "Oregon", "USpa": "Pennsylvania", "USri": "Rhode Island",
    "USsc": "South Carolina", "USsd": "South Dakota", "UStn": "Tennessee",
    "UStx": "Texas", "USut": "Utah", "USvt": "Vermont",
    "USva": "Virginia", "USwa": "Washington", "USwv": "West Virginia",
    "USwi": "Wisconsin", "USwy": "Wyoming", "USdc": "District of Columbia",
    "USas": "American Samoa", "USgu": "Guam", "USmp": "Northern Mariana Islands",
    "USpr": "Puerto Rico", "USvi": "U.S. Virgin Islands",
    
    # Canadian provinces and territories
    "CAab": "Alberta", "CAbc": "British Columbia", "CAmb": "Manitoba",
    "CAnb": "New Brunswick", "CAnl": "Newfoundland and Labrador",
    "CAns": "Nova Scotia", "CAnt": "Northwest Territories",
    "CAnu": "Nunavut", "CAon": "Ontario", "CApe": "Prince Edward Island",
    "CAqc": "Quebec", "CAsk": "Saskatchewan", "CAyt": "Yukon",
    
    # Australian states and territories
    "AUact": "Australian Capital Territory", "AUnt": "Northern Territory",
    "AUnsw": "New South Wales", "AUqld": "Queensland",
    "AUsa": "South Australia", "AUtas": "Tasmania",
    "AUvic": "Victoria", "AUwa": "Western Australia",
    
    # German federal states
    "DEbw": "Baden-Württemberg", "DEby": "Bavaria", "DEbe": "Berlin",
    "DEbb": "Brandenburg", "DEhb": "Bremen", "DEhh": "Hamburg",
    "DEhe": "Hesse", "DEMV": "Mecklenburg-Vorpommern", "DEni": "Lower Saxony",
    "DEnw": "North Rhine-Westphalia", "DErp": "Rhineland-Palatinate",
    "DEsl": "Saarland", "DEsn": "Saxony", "DEst": "Saxony-Anhalt",
    "DESH": "Schleswig-Holstein", "DEth": "Thuringia",
    
    # Indian states and union territories
    "INan": "Andhra Pradesh", "INar": "Arunachal Pradesh", "INas": "Assam",
    "INbr": "Bihar", "INch": "Chhattisgarh", "INga": "Goa",
    "INgj": "Gujarat", "INhr": "Haryana", "INhp": "Himachal Pradesh",
    "INjh": "Jharkhand", "INka": "Karnataka", "INkl": "Kerala",
    "INmp": "Madhya Pradesh", "INmh": "Maharashtra", "INmn": "Manipur",
    "INml": "Meghalaya", "INmz": "Mizoram", "INnl": "Nagaland",
    "INod": "Odisha", "INpb": "Punjab", "INrj": "Rajasthan",
    "INsk": "Sikkim", "INtn": "Tamil Nadu", "INtg": "Telangana",
    "INtr": "Tripura", "INup": "Uttar Pradesh", "INut": "Uttarakhand",
    "INwb": "West Bengal",
    
    # Brazilian states
    "BRac": "Acre", "BRal": "Alagoas", "BRap": "Amapá",
    "BRam": "Amazonas", "BRba": "Bahia", "BRce": "Ceará",
    "BRdf": "Distrito Federal", "BRes": "Espírito Santo", "BRgo": "Goiás",
    "BRma": "Maranhão", "BRmt": "Mato Grosso", "BRms": "Mato Grosso do Sul",
    "BRmg": "Minas Gerais", "BRpa": "Pará", "BRpb": "Paraíba",
    "BRpr": "Paraná", "BRpe": "Pernambuco", "BRpi": "Piauí",
    "BRrj": "Rio de Janeiro", "BRrn": "Rio Grande do Norte",
    "BRrs": "Rio Grande do Sul", "BRro": "Rondônia", "BRrr": "Roraima",
    "BRsc": "Santa Catarina", "BRsp": "São Paulo", "BRse": "Sergipe",
    "BRto": "Tocantins",
    
    # Mexican states
    "MXags": "Aguascalientes", "MXbc": "Baja California", "MXbcs": "Baja California Sur",
    "MXcam": "Campeche", "MXchp": "Chiapas", "MXchi": "Chihuahua",
    "MXcoa": "Coahuila", "MXcol": "Colima", "MXcmx": "Mexico City",
    "MXdur": "Durango", "MXgua": "Guanajuato", "MXgro": "Guerrero",
    "MXhid": "Hidalgo", "MXjal": "Jalisco", "MXmex": "Mexico",
    "MXmic": "Michoacán", "MXmor": "Morelos", "MXnay": "Nayarit",
    "MXnl": "Nuevo León", "MXoax": "Oaxaca", "MXpue": "Puebla",
    "MXque": "Querétaro", "MXqui": "Quintana Roo", "MXsan": "San Luis Potosí",
    "MXsin": "Sinaloa", "MXson": "Sonora", "MXtab": "Tabasco",
    "MXtam": "Tamaulipas", "MXtla": "Tlaxcala", "MXver": "Veracruz",
    "Mxyuc": "Yucatán", "MXzac": "Zacatecas",
    
    # Russian federal subjects
    "RUad": "Adygea", "RUal": "Altai Republic", "RUba": "Bashkortostan",
    "RUbu": "Buryatia", "RUce": "Chechnya", "RUcu": "Chuvashia",
    "RUda": "Dagestan", "RUin": "Ingushetia", "RUkb": "Kabardino-Balkaria",
    "RUkl": "Kalmykia", "RUkrc": "Karachay-Cherkessia", "RUka": "Karelia",
    "RUko": "Komi", "RUme": "Mari El", "RUmo": "Mordovia",
    "RUsa": "Sakha", "RUse": "North Ossetia", "RUtu": "Tatarstan",
    "RUty": "Tuva", "RUud": "Udmurtia",
    
    # Japanese prefectures
    "JPhk": "Hokkaido", "JPaom": "Aomori", "JPiw": "Iwate",
    "JPmi": "Miyagi", "JPak": "Akita", "JPya": "Yamagata",
    "JPfu": "Fukushima", "JPib": "Ibaraki", "JPto": "Tochigi",
    "JPgu": "Gunma", "JPsai": "Saitama", "JPch": "Chiba",
    "JPty": "Tokyo", "JPka": "Kanagawa", "JPni": "Niigata",
    "JPto": "Toyama", "JPis": "Ishikawa", "JPfu": "Fukui",
    "JPya": "Yamanashi", "JPna": "Nagano", "JPgi": "Gifu",
    "JPsh": "Shizuoka", "JPaic": "Aichi", "JPme": "Mie",
    "JPsh": "Shiga", "JPky": "Kyoto", "JPos": "Osaka",
    "JPhy": "Hyogo", "JPna": "Nara", "JPwa": "Wakayama",
    "JPto": "Tottori", "JPsh": "Shimane", "JPok": "Okayama",
    "JPhi": "Hiroshima", "JPya": "Yamaguchi", "JPto": "Tokushima",
    "JPka": "Kagawa", "JPeh": "Ehime", "JPko": "Kochi",
    "JPfu": "Fukuoka", "JPsag": "Saga", "JPna": "Nagasaki",
    "JPku": "Kumamoto", "JPo": "Oita", "JPmi": "Miyazaki",
    "JPka": "Kagoshima", "JPok": "Okinawa",
    
    # Argentine provinces
    "ARba": "Buenos Aires", "ARca": "Catamarca", "ARch": "Chaco",
    "ARct": "Chubut", "ARco": "Córdoba", "ARcr": "Corrientes",
    "ARer": "Entre Ríos", "ARfo": "Formosa", "ARju": "Jujuy",
    "ARlp": "La Pampa", "ARlr": "La Rioja", "ARme": "Mendoza",
    "ARmi": "Misiones", "ARne": "Neuquén", "ARrn": "Río Negro",
    "ARsa": "Salta", "ARsj": "San Juan", "ARsl": "San Luis",
    "ARsc": "Santa Cruz", "ARsf": "Santa Fe", "ARse": "Santiago del Estero",
    "ARtf": "Tierra del Fuego", "ARtu": "Tucumán",
    
    # South African provinces
    "ZAec": "Eastern Cape", "ZAfs": "Free State", "ZAgp": "Gauteng",
    "ZAkz": "KwaZulu-Natal", "ZAlp": "Limpopo", "ZAnp": "Mpumalanga",
    "ZAnc": "Northern Cape", "ZAnw": "North West", "ZAwc": "Western Cape",
    
    # Italian regions
    "ITab": "Abruzzo", "ITba": "Basilicata", "ITca": "Calabria",
    "ITcm": "Campania", "ITem": "Emilia-Romagna", "ITfr": "Friuli-Venezia Giulia",
    "ITla": "Lazio", "ITli": "Liguria", "ITlo": "Lombardy",
    "ITma": "Marche", "ITmo": "Molise", "ITpi": "Piedmont",
    "ITpu": "Puglia", "ITsa": "Sardinia", "ITsi": "Sicily",
    "ITto": "Tuscany", "ITtr": "Trentino-Alto Adige", "ITum": "Umbria",
    "ITva": "Valle d'Aosta", "ITve": "Veneto",
    
    # Spanish autonomous communities
    "ESan": "Andalusia", "ESar": "Aragon", "ESas": "Asturias",
    "EScb": "Cantabria", "EScl": "Castile and León", "EScm": "Castile-La Mancha",
    "EScn": "Canary Islands", "ESct": "Catalonia", "ESex": "Extremadura",
    "ESga": "Galicia", "ESib": "Balearic Islands", "ESmc": "Madrid",
    "ESmu": "Murcia", "ESna": "Navarre", "ESpv": "Basque Country",
    "ESri": "La Rioja", "ESvc": "Valencia",
    
    # Dutch provinces
    "NLdr": "Drenthe", "NLfl": "Flevoland", "NLfr": "Friesland",
    "NLge": "Gelderland", "NLgr": "Groningen", "NLli": "Limburg",
    "NLnb": "North Brabant", "NLnh": "North Holland", "NLov": "Overijssel",
    "NLut": "Utrecht", "NLze": "Zeeland", "NLzh": "South Holland",
    
    # Swedish counties
    "SEbl": "Blekinge", "SEda": "Dalarna", "SEga": "Gävleborg",
    "SEgo": "Gotland", "SEha": "Halland", "SEja": "Jämtland",
    "SEjo": "Jönköping", "SEka": "Kalmar", "SEkr": "Kronoberg",
    "SEno": "Norrbotten", "SEsk": "Skåne", "SEst": "Stockholm",
    "SEup": "Uppsala", "SEvb": "Värmland", "SEvg": "Västerbotten",
    "SEvn": "Västernorrland", "SEvt": "Västmanland", "SEvl": "Västra Götaland",
    "SEog": "Örebro", "SEor": "Östergötland",
    
    # Norwegian counties
    "NOag": "Agder", "NOin": "Innlandet", "NOmr": "Møre og Romsdal",
    "NOnn": "Nordland", "NOos": "Oslo", "NOro": "Rogaland",
    "NOtr": "Troms og Finnmark", "NOtd": "Trøndelag", "NOve": "Vestfold og Telemark",
    "NOvl": "Vestland", "NOvi": "Viken",
    
    # Danish regions
    "DKh": "Capital Region", "DKmj": "Central Jutland", "DKnj": "North Jutland",
    "DKsj": "Region of Southern Denmark", "DKze": "Zealand",
    
    # Finnish regions
    "FIah": "Åland Islands", "FIca": "Central Finland", "FIce": "Central Ostrobothnia",
    "FIka": "Kainuu", "FIke": "Kanta-Häme", "FIko": "Kymenlaakso",
    "FIla": "Lapland", "FImr": "Middle Ostrobothnia", "FIno": "North Karelia",
    "FInb": "Northern Ostrobothnia", "FIns": "Northern Savonia", "FIos": "Ostrobothnia",
    "FIpa": "Päijänne Tavastia", "FIpi": "Pirkanmaa", "FIpo": "Pohjois-Pohjanmaa",
    "FIps": "Pohjois-Savo", "FIph": "Päijät-Häme", "FIsm": "Satakunta",
    "FIsk": "Southern Karelia", "FIsb": "Southern Ostrobothnia", "FIss": "Southern Savonia",
    "FIta": "Tavastia Proper", "FIum": "Uusimaa",
    
    # Polish voivodeships
    "PLds": "Lower Silesian", "PLkp": "Kuyavian-Pomeranian", "PLlb": "Lublin",
    "PLld": "Łódź", "PLlu": "Lubusz", "PLma": "Lesser Poland",
    "PLmz": "Masovian", "PLop": "Opole", "PLpd": "Podlaskie",
    "PLpk": "Podkarpackie", "PLpm": "Pomeranian", "PLsk": "Silesian",
    "PLsl": "Świętokrzyskie", "PLwn": "Warmian-Masurian", "PLwp": "Greater Poland",
    "PLzp": "West Pomeranian",
    
    # Czech regions
    "CZjc": "Central Bohemian", "CZjm": "South Moravian", "CZka": "Karlovy Vary",
    "CZkr": "Hradec Králové", "CZli": "Liberec", "CZmo": "Moravian-Silesian",
    "CZol": "Olomouc", "CZpa": "Pardubice", "CZpl": "Plzeň",
    "CZpr": "Prague", "CZus": "Ústí nad Labem",
    "CZvy": "Vysočina", "CZzl": "Zlín",
    
    # Hungarian counties
    "HUba": "Baranya", "HUbe": "Békés", "HUbs": "Bács-Kiskun",
    "HUcs": "Csongrád", "HUfe": "Fejér", "HUgy": "Győr-Moson-Sopron",
    "HUha": "Hajdú-Bihar", "HUhe": "Heves", "HUja": "Jász-Nagykun-Szolnok",
    "HUke": "Komárom-Esztergom", "HUno": "Nógrád", "HUpe": "Pest",
    "HUsa": "Somogy", "HUsz": "Szabolcs-Szatmár-Bereg", "HUto": "Tolna",
    "HUva": "Vas", "HUve": "Veszprém", "HUza": "Zala",
    
    # Romanian counties
    "ROab": "Alba", "ROar": "Arad", "ROag": "Argeș",
    "RObc": "Bacău", "RObh": "Bihor", "RObn": "Bistrița-Năsăud",
    "RObt": "Botoșani", "RObv": "Brașov", "RObr": "Brăila",
    "RObz": "Buzău", "ROcs": "Caraș-Severin", "ROcl": "Călărași",
    "ROcj": "Cluj", "ROct": "Constanța", "ROcv": "Covasna",
    "ROdb": "Dâmbovița", "ROdj": "Dolj", "ROgl": "Galați",
    "ROgr": "Giurgiu", "ROgj": "Gorj", "ROhr": "Harghita",
    "ROhd": "Hunedoara", "ROil": "Ialomița", "ROis": "Iași",
    "ROif": "Ilfov", "ROmm": "Maramureș", "ROmh": "Mehedinți",
    "ROms": "Mureș", "ROnt": "Neamț", "ROot": "Olt",
    "ROph": "Prahova", "ROsm": "Sălaj", "ROsb": "Sibiu",
    "ROsv": "Suceava", "ROtr": "Teleorman", "ROtm": "Timiș",
    "ROtl": "Tulcea", "ROvs": "Vâlcea", "ROvn": "Vaslui",
    "ROvr": "Vrancea",
    
    # Bulgarian provinces
    "BGbl": "Blagoevgrad", "BGbg": "Burgas", "BGvd": "Vidin",
    "BGvr": "Vratsa", "BGga": "Gabrovo", "BGdv": "Dobrich",
    "BGkr": "Kardzhali", "BGky": "Kyustendil", "BGlv": "Lovech",
    "BGmn": "Montana", "BGpa": "Pazardzhik", "BGpv": "Pernik",
    "BGpn": "Pleven", "BGpl": "Plovdiv", "BGrz": "Razgrad",
    "BGrs": "Ruse", "BGsl": "Silistra", "BGsv": "Sliven",
    "BGsm": "Smolyan", "BGsg": "Sofia", "BGsz": "Sofia City",
    "BGst": "Stara Zagora", "BGta": "Targovishte", "BGha": "Haskovo",
    "BGsh": "Shumen", "BGya": "Yambol",
    
    # Greek regions
    "GRat": "Attica", "GRce": "Central Greece", "GRcm": "Central Macedonia",
    "GRcr": "Crete", "GRea": "East Macedonia and Thrace", "GRep": "Epirus",
    "GRio": "Ionian Islands", "GRno": "North Aegean", "GRpe": "Peloponnese",
    "GRso": "South Aegean", "GRth": "Thessaly", "GRwe": "West Greece",
    "GRwm": "West Macedonia",
    
    # Turkish provinces
    "TRad": "Adana", "TRadı": "Adıyaman", "TRaf": "Afyonkarahisar",
    "TRag": "Ağrı", "TRak": "Aksaray", "TRam": "Amasya",
    "TRan": "Ankara", "TRant": "Antalya", "TRar": "Ardahan",
    "TRart": "Artvin", "TRay": "Aydın", "TRba": "Balıkesir",
    "TRbt": "Bartın", "TRbm": "Batman", "TRby": "Bayburt",
    "TRbi": "Bilecik", "TRbg": "Bingöl", "TRbl": "Bitlis",
    "TRbo": "Bolu", "TRbu": "Burdur", "TRbs": "Bursa",
    "TRca": "Çanakkale", "TRck": "Çankırı", "TRcr": "Çorum",
    "TRde": "Denizli", "TRdi": "Diyarbakır", "TRdu": "Düzce",
    "TRea": "Edirne", "TRez": "Elazığ", "TRer": "Erzincan",
    "TReu": "Erzurum", "TRes": "Eskişehir", "TRga": "Gaziantep",
    "TRgi": "Giresun", "TRgu": "Gümüşhane", "TRha": "Hakkari",
    "TRht": "Hatay", "TRig": "Iğdır", "TRis": "Isparta",
    "TRst": "Istanbul", "TRiz": "İzmir", "TRka": "Kahramanmaraş",
    "TRkb": "Karabük", "TRkm": "Karaman", "TRks": "Kars",
    "TRkt": "Kastamonu", "TRky": "Kayseri", "TRki": "Kırıkkale",
    "TRkl": "Kırklareli", "TRkr": "Kırşehir", "TRkls": "Kilis",
    "TRko": "Kocaeli", "TRkn": "Konya", "TRku": "Kütahya",
    "TRma": "Malatya", "TRmn": "Manisa", "TRmd": "Mardin",
    "TRme": "Mersin", "TRmu": "Muğla", "TRmş": "Muş",
    "TRne": "Nevşehir", "TRni": "Niğde", "TRor": "Ordu",
    "TRos": "Osmaniye", "TRri": "Rize", "TRsa": "Sakarya",
    "TRsm": "Samsun", "TRsu": "Şanlıurfa", "TRsi": "Siirt",
    "TRsp": "Sinop", "TRşr": "Şırnak", "TRsv": "Sivas",
    "TRte": "Tekirdağ", "TRto": "Tokat", "TRtr": "Trabzon",
    "TRtu": "Tunceli", "TRus": "Uşak", "TRva": "Van",
    "TRya": "Yalova", "TRyo": "Yozgat", "TRza": "Zonguldak",
    
    # Iranian provinces
    "IRal": "Alborz", "IRar": "Ardabil", "IRaz": "East Azerbaijan",
    "IRwz": "West Azerbaijan", "IRbu": "Bushehr", "IRch": "Chaharmahal and Bakhtiari",
    "IRfa": "Fars", "IRgi": "Gilan", "IRgo": "Golestan",
    "IRha": "Hamadan", "IRho": "Hormozgan", "IRil": "Ilam",
    "IRis": "Isfahan", "IRka": "Kerman", "IRks": "Kermanshah",
    "IRkh": "Khorasan", "IRnk": "North Khorasan", "IRrk": "Razavi Khorasan",
    "IRsk": "South Khorasan", "IRko": "Kohgiluyeh and Boyer-Ahmad", "IRku": "Kurdistan",
    "IRlo": "Lorestan", "IRma": "Markazi", "IRmz": "Mazandaran",
    "IRqa": "Qazvin", "IRqm": "Qom", "IRse": "Semnan",
    "IRsi": "Sistan and Baluchestan", "IRte": "Tehran", "IRya": "Yazd",
    "IRza": "Zanjan",
    
    # Pakistani provinces
    "PKba": "Balochistan", "PKgb": "Gilgit-Baltistan", "PKis": "Islamabad Capital Territory",
    "PKkp": "Khyber Pakhtunkhwa", "PKpb": "Punjab", "PKsd": "Sindh",
    "PKaj": "Azad Jammu and Kashmir",
    
    # Thai provinces
    "THac": "Amnat Charoen", "THan": "Ang Thong", "THbu": "Bueng Kan",
    "THbr": "Buriram", "THch": "Chachoengsao", "THcn": "Chai Nat",
    "THcy": "Chaiyaphum", "THcb": "Chanthaburi", "THcm": "Chiang Mai",
    "THcr": "Chiang Rai", "THco": "Chonburi", "THcp": "Chumphon",
    "THka": "Kalasin", "THkp": "Kamphaeng Phet", "THkc": "Kanchanaburi",
    "THkk": "Khon Kaen", "THkr": "Krabi", "THla": "Lamphun",
    "THlg": "Lampang", "THle": "Loei", "THlo": "Lopburi",
    "THma": "Mae Hong Son", "THms": "Maha Sarakham", "THmk": "Mukdahan",
    "THna": "Nakhon Nayok", "THnp": "Nakhon Pathom", "THnph": "Nakhon Phanom",
    "THnr": "Nakhon Ratchasima", "THns": "Nakhon Sawan", "THnst": "Nakhon Si Thammarat",
    "THnn": "Nan", "THnw": "Narathiwat", "THno": "Nong Bua Lamphu",
    "THnk": "Nong Khai", "THnt": "Nonthaburi", "THpa": "Pathum Thani",
    "THpt": "Pattani", "THpe": "Phang Nga", "THph": "Phatthalung",
    "THpy": "Phayao", "THpc": "Phetchabun", "THpb": "Phetchaburi",
    "THpi": "Phichit", "THpl": "Phitsanulok", "THpaa": "Phra Nakhon Si Ayutthaya",
    "THpr": "Phrae", "THpk": "Phuket", "THpch": "Prachinburi",
    "THpkk": "Prachuap Khiri Khan", "THra": "Ranong", "THrb": "Ratchaburi",
    "THry": "Rayong", "THri": "Roi Et", "THsa": "Sa Kaeo",
    "THsk": "Sakon Nakhon", "THsp": "Samut Prakan", "THss": "Samut Sakhon",
    "THssg": "Samut Songkhram", "THsb": "Saraburi", "THst": "Satun",
    "THsi": "Si Sa Ket", "THsg": "Sing Buri", "THso": "Songkhla",
    "THsu": "Sukhothai", "THsb": "Suphan Buri", "THstn": "Surat Thani",
    "THsr": "Surin", "THtk": "Tak", "THtr": "Trang",
    "THtt": "Trat", "THub": "Ubon Ratchathani", "THud": "Udon Thani",
    "THut": "Uthai Thani", "THudt": "Uttaradit", "THya": "Yala",
    "THys": "Yasothon",
    
    # Vietnamese provinces
    "VNag": "An Giang", "VNba": "Bà Rịa-Vũng Tàu", "VNbc": "Bắc Giang",
    "VNbk": "Bắc Kạn", "VNbl": "Bạc Liêu", "VNbn": "Bắc Ninh",
    "VNbt": "Bến Tre", "VNca": "Cà Mau", "VNcb": "Cao Bằng",
    "VNcm": "Cần Thơ", "VNdb": "Điện Biên",
    "VNdg": "Đắk Lắk", "VNdn": "Đắk Nông", "VNdo": "Đồng Nai",
    "VNdt": "Đồng Tháp", "VNgl": "Gia Lai", "VNha": "Hà Giang",
    "VNhn": "Hà Nam", "VNhnh": "Hà Nội", "VNht": "Hà Tĩnh",
    "VNhd": "Hải Dương", "VNhp": "Hải Phòng", "VNHg": "Hậu Giang",
    "VNho": "Hòa Bình", "VNhy": "Hưng Yên", "VNkg": "Kiên Giang",
    "VNkt": "Kon Tum", "VNla": "Lai Châu", "VNld": "Lâm Đồng",
    "VNls": "Lạng Sơn", "VNlc": "Lào Cai", "VNln": "Long An",
    "VNna": "Nam Định", "VNng": "Nghệ An", "VNnb": "Ninh Bình",
    "VNnt": "Ninh Thuận", "VNph": "Phú Thọ", "VNpy": "Phú Yên",
    "VNqb": "Quảng Bình", "VNqd": "Quảng Nam",
    "VNqg": "Quảng Ngãi", "VNqn": "Quảng Ninh", "VNqt": "Quảng Trị",
    "VNso": "Sóc Trăng", "VNsl": "Sơn La", "VNta": "Tây Ninh",
    "VNtb": "Thái Bình", "VNth": "Thái Nguyên", "VNTn": "Thanh Hóa",
    "VNtt": "Thừa Thiên-Huế", "VNti": "Tiền Giang", "VNto": "Tuyên Quang",
    "VNtv": "Trà Vinh", "VNvl": "Vĩnh Long", "VNvp": "Vĩnh Phúc",
    "VNyb": "Yên Bái",
    
    # Philippine provinces
    "PHab": "Abra", "PHag": "Agusan del Norte", "PHas": "Agusan del Sur",
    "PHai": "Aklan", "PHal": "Albay", "PHan": "Antique",
    "PHap": "Apayao", "PHau": "Aurora", "PHba": "Basilan",
    "PHbt": "Bataan", "PHbs": "Batanes", "PHbg": "Batangas",
    "PHbe": "Benguet", "PHbi": "Biliran", "PHbo": "Bohol",
    "PHbu": "Bukidnon", "PHbl": "Bulacan", "PHca": "Cagayan",
    "PHcd": "Cagayan de Oro", "PHcn": "Camarines Norte", "PHcs": "Camarines Sur",
    "PHcg": "Camiguin", "PHcp": "Capiz", "PHct": "Catanduanes",
    "PHcv": "Cavite", "PHce": "Cebu", "PHco": "Cotabato",
    "PHda": "Davao del Norte", "PHds": "Davao del Sur", "PHdo": "Davao Occidental",
    "PHdr": "Davao Oriental", "PHdi": "Dinagat Islands", "PHea": "Eastern Samar",
    "PHgu": "Guimaras", "PHif": "Ifugao", "PHil": "Ilocos Norte",
    "PHil": "Ilocos Sur", "PHil": "Iloilo", "PHis": "Isabela",
    "PHka": "Kalinga", "PHla": "La Union", "PHlg": "Laguna",
    "PHln": "Lanao del Norte", "PHls": "Lanao del Sur", "PHle": "Leyte",
    "PHma": "Maguindanao", "PHmq": "Marinduque", "PHms": "Masbate",
    "PHmi": "Mindoro Occidental", "PHmo": "Mindoro Oriental", "PHmc": "Misamis Occidental",
    "PHme": "Misamis Oriental", "PHmp": "Mountain Province", "PHna": "Negros Occidental",
    "PHne": "Negros Oriental", "PHno": "Northern Samar", "PHnu": "Nueva Ecija",
    "PHnv": "Nueva Vizcaya", "PHpa": "Palawan", "PHpm": "Pampanga",
    "PHpg": "Pangasinan", "PHqu": "Quezon", "PHqi": "Quirino",
    "PHri": "Rizal", "PHro": "Romblon", "PHsa": "Samar",
    "PHsg": "Sarangani", "PHsi": "Siquijor", "PHso": "Sorsogon",
    "PHsc": "South Cotabato", "PHsl": "Southern Leyte", "PHsu": "Sultan Kudarat",
    "PHsu": "Sulu", "PHsn": "Surigao del Norte", "PHss": "Surigao del Sur",
    "PHta": "Tarlac", "PHtw": "Tawi-Tawi", "PHza": "Zambales",
    "PHzn": "Zamboanga del Norte", "PHzs": "Zamboanga del Sur", "PHzb": "Zamboanga Sibugay",
    
    # Malaysian states
    "MYjh": "Johor", "MYkd": "Kedah", "MYkl": "Kelantan",
    "MYml": "Melaka", "MYns": "Negeri Sembilan", "MYph": "Pahang",
    "MYpk": "Perak", "MYpl": "Perlis", "MYpg": "Pulau Pinang",
    "MYsb": "Sabah", "MYsr": "Sarawak", "MYsl": "Selangor",
    "MYtr": "Terengganu", "MYkl": "Kuala Lumpur", "MYlb": "Labuan",
    "MYpj": "Putrajaya",
    
    # Indonesian provinces
    "IDac": "Aceh", "IDba": "Bali", "IDbb": "Bangka Belitung",
    "IDbt": "Banten", "IDbe": "Bengkulu", "IDjt": "Central Java",
    "IDji": "East Java", "IDgo": "Gorontalo", "IDjk": "Jakarta",
    "IDja": "Jambi", "IDla": "Lampung", "IDml": "Maluku",
    "IDmu": "North Maluku", "IDnt": "North Sulawesi", "IDsa": "North Sumatra",
    "IDpa": "Papua", "IDri": "Riau", "IDri": "Riau Islands",
    "IDsg": "Southeast Sulawesi", "IDsn": "South Sulawesi", "IDss": "South Sumatra",
    "IDsw": "Southwest Papua", "IDst": "Central Sulawesi", "IDsu": "West Java",
    "IDsb": "West Nusa Tenggara", "IDsp": "West Papua", "IDsi": "West Sulawesi",
    "IDss": "West Sumatra",
    
    # New Zealand regions
    "NZau": "Auckland", "NZbo": "Bay of Plenty", "NZca": "Canterbury",
    "NZgi": "Gisborne", "NZha": "Hawke's Bay", "NZma": "Manawatu-Wanganui",
    "NZma": "Marlborough", "NZne": "Nelson", "NZno": "Northland",
    "NZot": "Otago", "NZso": "Southland", "NZta": "Taranaki",
    "NZwa": "Waikato", "NZwe": "Wellington", "NZwe": "Westland",
    
    # Chilean regions
    "CLai": "Aisén", "CLan": "Antofagasta", "CLar": "Araucanía",
    "CLar": "Arica and Parinacota", "CLat": "Atacama", "CLbi": "Biobío",
    "CLco": "Coquimbo", "CLli": "Libertador General Bernardo O'Higgins",
    "CLll": "Los Lagos", "CLlr": "Los Ríos", "CLma": "Magallanes",
    "CLma": "Maule", "CLme": "Metropolitan", "CLta": "Tarapacá",
    "CLva": "Valparaíso",
    
    # Colombian departments
    "COam": "Amazonas", "COan": "Antioquia", "COar": "Arauca",
    "COat": "Atlántico", "CObo": "Bolívar", "CObo": "Boyacá",
    "COca": "Caldas", "COca": "Caquetá", "COca": "Casanare",
    "COca": "Cauca", "COce": "Cesar", "COch": "Chocó",
    "COco": "Córdoba", "COcu": "Cundinamarca", "COgu": "Guainía",
    "COgu": "Guaviare", "COhu": "Huila", "COla": "La Guajira",
    "COma": "Magdalena", "COme": "Meta", "COna": "Nariño",
    "CONS": "Norte de Santander", "COpu": "Putumayo", "COqu": "Quindío",
    "COri": "Risaralda", "COsa": "Santander", "COsu": "Sucre",
    "COto": "Tolima", "COva": "Valle del Cauca", "COva": "Vaupés",
    "COvi": "Vichada",
    
    # Peruvian regions
    "PEam": "Amazonas", "PEan": "Ancash", "PEap": "Apurímac",
    "PEar": "Arequipa", "PEay": "Ayacucho", "PEca": "Cajamarca",
    "PEca": "Callao", "PEcu": "Cusco", "PEhu": "Huancavelica",
    "PEhu": "Huánuco", "PEic": "Ica", "PEju": "Junín",
    "PElb": "Lambayeque", "PElm": "Lima", "PElr": "Loreto",
    "PEma": "Madre de Dios", "PEmo": "Moquegua", "PEpa": "Pasco",
    "PEpi": "Piura", "PEpu": "Puno", "PEsa": "San Martín",
    "PEta": "Tacna", "PEtu": "Tumbes", "PEuc": "Ucayali",
    
    # Venezuelan states
    "VEam": "Amazonas", "VEan": "Anzoátegui", "VEap": "Apure",
    "VEar": "Aragua", "VEba": "Barinas", "VEbo": "Bolívar",
    "VEca": "Carabobo", "VEco": "Cojedes", "VEde": "Delta Amacuro",
    "VEdf": "Federal District", "VEfa": "Falcón", "VEgu": "Guárico",
    "VEla": "Lara", "VEme": "Mérida", "VEmi": "Miranda",
    "VEmo": "Monagas", "VEne": "Nueva Esparta", "VEpo": "Portuguesa",
    "VEsj": "Sucre", "VEta": "Táchira", "VEtr": "Trujillo",
    "VEva": "Vargas", "VEya": "Yaracuy", "VEzu": "Zulia",
    
    # Uruguayan departments
    "UYar": "Artigas", "UYca": "Canelones", "UYce": "Cerro Largo",
    "UYco": "Colonia", "UYdu": "Durazno", "UYfl": "Flores",
    "UYfd": "Florida", "UYla": "Lavalleja", "UYma": "Maldonado",
    "UYmo": "Montevideo", "UYpa": "Paysandú", "UYri": "Río Negro",
    "UYro": "Rocha", "UYsa": "Salto", "UYsj": "San José",
    "UYso": "Soriano", "UYta": "Tacuarembó", "UYtt": "Treinta y Tres",
    
    # Paraguayan departments
    "PYag": "Alto Paraguay", "PYag": "Alto Paraná", "PYam": "Amambay",
    "PYas": "Asunción", "PYbo": "Boquerón", "PYca": "Caaguazú",
    "PYca": "Caazapá", "PYca": "Canindeyú", "PYce": "Central",
    "PYco": "Concepción", "PYco": "Cordillera", "PYgu": "Guairá",
    "PYit": "Itapúa", "PYmi": "Misiones", "PYne": "Ñeembucú",
    "PYpa": "Paraguarí", "PYpr": "Presidente Hayes", "PYsa": "San Pedro",
    
    # Bolivian departments
    "BOch": "Chuquisaca", "BOco": "Cochabamba", "BObe": "Beni",
    "BOla": "La Paz", "BOor": "Oruro", "BOpa": "Pando",
    "BOpo": "Potosí", "BOsa": "Santa Cruz", "BOta": "Tarija",
    
    # Ecuadorian provinces
    "ECaz": "Azuay", "ECbo": "Bolívar", "ECca": "Cañar",
    "ECca": "Carchi", "ECch": "Chimborazo", "ECco": "Cotopaxi",
    "ECel": "El Oro", "ECes": "Esmeraldas", "ECga": "Galápagos",
    "ECgu": "Guayas", "ECim": "Imbabura", "EClo": "Loja",
    "EClr": "Los Ríos", "ECma": "Manabí", "ECmo": "Morona-Santiago",
    "ECna": "Napo", "ECor": "Orellana", "ECpa": "Pastaza",
    "ECpi": "Pichincha", "ECse": "Santa Elena", "ECse": "Santo Domingo de los Tsáchilas",
    "ECsu": "Sucumbíos", "ECtu": "Tungurahua", "ECza": "Zamora-Chinchipe",
    
    # Country codes
    "ccaf": "Afghanistan", "ccal": "Albania", "ccdz": "Algeria",
    "ccad": "Andorra", "ccao": "Angola", "ccag": "Antigua and Barbuda",
    "ccar": "Argentina", "ccam": "Armenia", "ccau": "Australia",
    "ccat": "Austria", "ccaz": "Azerbaijan", "ccbs": "Bahamas",
    "ccbh": "Bahrain", "ccbd": "Bangladesh", "ccbb": "Barbados",
    "ccby": "Belarus", "ccbe": "Belgium", "ccbz": "Belize",
    "ccbj": "Benin", "ccbt": "Bhutan", "ccbo": "Bolivia",
    "ccba": "Bosnia and Herzegovina", "ccbw": "Botswana", "ccbr": "Brazil",
    "ccbn": "Brunei", "ccbg": "Bulgaria", "ccbf": "Burkina Faso",
    "ccbi": "Burundi", "cckh": "Cambodia", "cccm": "Cameroon",
    "ccca": "Canada", "cccv": "Cape Verde", "cccf": "Central African Republic",
    "cctd": "Chad", "cccl": "Chile", "cccn": "China",
    "ccco": "Colombia", "cckm": "Comoros", "cccg": "Congo",
    "cccr": "Costa Rica", "cchr": "Croatia", "cccu": "Cuba",
    "cccy": "Cyprus", "cccz": "Czech Republic", "cccd": "Democratic Republic of the Congo",
    "ccdk": "Denmark", "ccdj": "Djibouti", "ccdm": "Dominica",
    "ccdo": "Dominican Republic", "ccec": "Ecuador", "cceg": "Egypt",
    "ccsv": "El Salvador", "ccgq": "Equatorial Guinea", "ccer": "Eritrea",
    "ccee": "Estonia", "ccet": "Ethiopia", "ccfj": "Fiji",
    "ccfi": "Finland", "ccfr": "France", "ccga": "Gabon",
    "ccgm": "Gambia", "ccge": "Georgia", "ccde": "Germany",
    "ccgh": "Ghana", "ccgr": "Greece", "ccgd": "Grenada",
    "ccgt": "Guatemala", "ccgn": "Guinea", "ccgw": "Guinea-Bissau",
    "ccgy": "Guyana", "ccht": "Haiti", "cchn": "Honduras",
    "cchu": "Hungary", "ccis": "Iceland", "ccin": "India",
    "ccid": "Indonesia", "ccir": "Iran", "cciq": "Iraq",
    "ccie": "Ireland", "ccil": "Israel", "ccit": "Italy",
    "cciv": "Ivory Coast", "ccjm": "Jamaica", "ccjp": "Japan",
    "ccjo": "Jordan", "cckz": "Kazakhstan", "ccke": "Kenya",
    "ccki": "Kiribati", "ccxk": "Kosovo", "cckw": "Kuwait",
    "cckg": "Kyrgyzstan", "ccla": "Laos", "cclv": "Latvia",
    "cclb": "Lebanon", "ccls": "Lesotho", "cclr": "Liberia",
    "ccly": "Libya", "ccli": "Liechtenstein", "cclt": "Lithuania",
    "cclu": "Luxembourg", "ccmk": "Macedonia", "ccmg": "Madagascar",
    "ccmw": "Malawi", "ccmy": "Malaysia", "ccmv": "Maldives",
    "ccml": "Mali", "ccmt": "Malta", "ccmh": "Marshall Islands",
    "ccmr": "Mauritania", "ccmu": "Mauritius", "ccmx": "Mexico",
    "ccfm": "Micronesia", "ccmd": "Moldova", "ccmc": "Monaco",
    "ccmn": "Mongolia", "ccme": "Montenegro", "ccma": "Morocco",
    "ccmz": "Mozambique", "ccmm": "Myanmar", "ccna": "Namibia",
    "ccnr": "Nauru", "ccnp": "Nepal", "ccnl": "Netherlands",
    "ccnz": "New Zealand", "ccni": "Nicaragua", "ccne": "Niger",
    "ccng": "Nigeria", "cckp": "North Korea", "ccno": "Norway",
    "ccom": "Oman", "ccpk": "Pakistan", "ccpw": "Palau",
    "ccps": "Palestine", "ccpa": "Panama", "ccpg": "Papua New Guinea",
    "ccpy": "Paraguay", "ccpe": "Peru", "ccph": "Philippines",
    "ccpl": "Poland", "ccpt": "Portugal", "ccqa": "Qatar",
    "ccro": "Romania", "ccru": "Russia", "ccrw": "Rwanda",
    "cckn": "Saint Kitts and Nevis", "cclc": "Saint Lucia",
    "ccvc": "Saint Vincent and the Grenadines", "ccws": "Samoa",
    "ccsm": "San Marino", "ccst": "Sao Tome and Principe", "ccsa": "Saudi Arabia",
    "ccsn": "Senegal", "ccrs": "Serbia", "ccsc": "Seychelles",
    "ccsl": "Sierra Leone", "ccsg": "Singapore", "ccsk": "Slovakia",
    "ccsi": "Slovenia", "ccsb": "Solomon Islands", "ccso": "Somalia",
    "ccza": "South Africa", "cckr": "South Korea", "ccss": "South Sudan",
    "cces": "Spain", "cclk": "Sri Lanka", "ccsd": "Sudan",
    "ccsr": "Suriname", "ccsz": "Eswatini", "ccse": "Sweden",
    "ccch": "Switzerland", "ccsy": "Syria", "cctw": "Taiwan",
    "cctj": "Tajikistan", "cctz": "Tanzania", "ccth": "Thailand",
    "cctl": "Timor-Leste", "cctg": "Togo", "ccto": "Tonga",
    "cctt": "Trinidad and Tobago", "cctn": "Tunisia", "cctr": "Turkey",
    "cctm": "Turkmenistan", "cctv": "Tuvalu", "ccug": "Uganda",
    "ccua": "Ukraine", "ccae": "United Arab Emirates", "ccgb": "England",
    "ccwl": "Wales", "ccscot": "Scotland", "ccuk": "Northern Ireland",
    "ccus": "United States", "ccuy": "Uruguay", "ccuz": "Uzbekistan",
    "ccvu": "Vanuatu", "ccva": "Vatican City", "ccve": "Venezuela",
    "ccvn": "Vietnam", "ccye": "Yemen", "cczm": "Zambia",
    "cczw": "Zimbabwe",
    
    # Nationalities
    "pccaf": "Afghan", "pccal": "Albanian", "pccdz": "Algerian",
    "pccad": "Andorran", "pccao": "Angolan", "pccag": "Antiguan",
    "pccar": "Argentine", "pccam": "Armenian", "pccau": "Australian",
    "pccat": "Austrian", "pccaz": "Azerbaijani", "pccbs": "Bahamian",
    "pccbh": "Bahraini", "pccbd": "Bangladeshi", "pccbb": "Barbadian",
    "pccby": "Belarusian", "pccbe": "Belgian", "pccbz": "Belizean",
    "pccbj": "Beninese", "pccbt": "Bhutanese", "pccbo": "Bolivian",
    "pccba": "Bosnian", "pccbw": "Botswanan", "pccbr": "Brazilian",
    "pccbn": "Bruneian", "pccbg": "Bulgarian", "pccbf": "Burkinabe",
    "pccbi": "Burundian", "pcckh": "Cambodian", "pcccm": "Cameroonian",
    "pccca": "Canadian", "pcccv": "Cape Verdean", "pcccf": "Central African",
    "pcctd": "Chadian", "pcccl": "Chilean", "pcccn": "Chinese",
    "pccco": "Colombian", "pcckm": "Comorian", "pcccg": "Congolese",
    "pcccd": "Congolese", "pcccr": "Costa Rican", "pcchr": "Croatian",
    "pcccu": "Cuban", "pcccy": "Cypriot", "pcccz": "Czech",
    "pccdk": "Danish", "pccdj": "Djiboutian", "pccdm": "Dominican",
    "pccdo": "Dominican", "pccec": "Ecuadorian", "pcceg": "Egyptian",
    "pccsv": "Salvadoran", "pccgq": "Equatorial Guinean", "pccer": "Eritrean",
    "pccee": "Estonian", "pccet": "Ethiopian", "pccfj": "Fijian",
    "pccfi": "Finnish", "pccfr": "French", "pccga": "Gabonese",
    "pccgm": "Gambian", "pccge": "Georgian", "pccde": "German",
    "pccgh": "Ghanaian", "pccgr": "Greek", "pccgd": "Grenadian",
    "pccgt": "Guatemalan", "pccgn": "Guinean", "pccgw": "Guinea-Bissauan",
    "pccgy": "Guyanese", "pccht": "Haitian", "pcchn": "Honduran",
    "pcchu": "Hungarian", "pccis": "Icelandic", "pccin": "Indian",
    "pccid": "Indonesian", "pccir": "Iranian", "pcciq": "Iraqi",
    "pccie": "Irish", "pccil": "Israeli", "pccit": "Italian",
    "pcciv": "Ivorian", "pccjm": "Jamaican", "pccjp": "Japanese",
    "pccjo": "Jordanian", "pcckz": "Kazakhstani", "pccke": "Kenyan",
    "pccki": "I-Kiribati", "pccxk": "Kosovar", "pcckw": "Kuwaiti",
    "pcckg": "Kyrgyzstani", "pccla": "Laotian", "pcclv": "Latvian",
    "pcclb": "Lebanese", "pccls": "Lesothan", "pcclr": "Liberian",
    "pccly": "Libyan", "pccli": "Liechtensteiner", "pcclt": "Lithuanian",
    "pcclu": "Luxembourger", "pccmk": "Macedonian", "pccmg": "Malagasy",
    "pccmw": "Malawian", "pccmy": "Malaysian", "pccmv": "Maldivian",
    "pccml": "Malian", "pccmt": "Maltese", "pccmh": "Marshallese",
    "pccmr": "Mauritanian", "pccmu": "Mauritian", "pccmx": "Mexican",
    "pccfm": "Micronesian", "pccmd": "Moldovan", "pccmc": "Monacan",
    "pccmn": "Mongolian", "pccme": "Montenegro", "pccma": "Moroccan",
    "pccmz": "Mozambican", "pccmm": "Myanmar", "pccna": "Namibian",
    "pccnr": "Nauruan", "pccnp": "Nepalese", "pccnl": "Dutch",
    "pccnz": "New Zealander", "pccni": "Nicaraguan", "pccne": "Nigerien",
    "pccng": "Nigerian", "pcckp": "North Korean", "pccno": "Norwegian",
    "pccom": "Omani", "pccpk": "Pakistani", "pccpw": "Palauan",
    "pccps": "Palestinian", "pccpa": "Panamanian", "pccpg": "Papua New Guinean",
    "pccpy": "Paraguayan", "pccpe": "Peruvian", "pccph": "Filipino",
    "pccpl": "Polish", "pccpt": "Portuguese", "pccqa": "Qatari",
    "pccro": "Romanian", "pccru": "Russian", "pccrw": "Rwandan",
    "pcckn": "Kittitian", "pcclc": "Saint Lucian", "pccvc": "Vincentian",
    "pccws": "Samoan", "pccsm": "Sammarinese", "pccst": "Sao Tomean",
    "pccsa": "Saudi Arabian", "pccsn": "Senegalese", "pccrs": "Serbian",
    "pccsc": "Seychellois", "pccsl": "Sierra Leonean", "pccsg": "Singaporean",
    "pccsk": "Slovak", "pccsi": "Slovenian", "pccsb": "Solomon Islander",
    "pccso": "Somali", "pccza": "South African", "pcckr": "South Korean",
    "pccss": "South Sudanese", "pcces": "Spanish", "pcclk": "Sri Lankan",
    "pccsd": "Sudanese", "pccsr": "Surinamese", "pccsz": "Swazi",
    "pccse": "Swedish", "pccch": "Swiss", "pccsy": "Syrian",
    "pcctw": "Taiwanese", "pcctj": "Tajik", "pcctz": "Tanzanian",
    "pccth": "Thai", "pcctl": "Timorese", "pcctg": "Togolese",
    "pccto": "Tongan", "pcctt": "Trinidadian", "pcctn": "Tunisian",
    "pcctr": "Turkish", "pcctm": "Turkmen", "pcctv": "Tuvaluan",
    "pccug": "Ugandan", "pccua": "Ukrainian", "pccae": "Emirati",
    "pccgb": "English", "pccwh": "Welsh", "pccscot": "Scotland",
    "pccuk": "Northern Irish", "pccus": "United States", "pccuy": "Uruguayan",
    "pccuz": "Uzbek", "pccvu": "Vanuatuan", "pccva": "Vatican",
    "pccve": "Venezuelan", "pccvn": "Vietnamese", "pccye": "Yemeni",
    "pcczm": "Zambian", "pcczw": "Zimbabwean",
}
